export const REQUEST_DOMAIN_RULE = "REQUEST_DOMAIN_RULE";
export const RECEIVED_DOMAIN_RULE = "RECEIVED_DOMAIN_RULE";

export const REQUEST_REGISTERED_TINS = "REQUEST_REGISTERED_TINS";
export const RECEIVED_REGISTERED_TINS = "RECEIVED_REGISTERED_TINS";

export const REQUEST_PAYERS = "REQUEST_PAYERS";
export const RECEIVED_PAYERS = "RECEIVED_PAYERS";
